@startuml CU-AB-11-registrar-resolucion

left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome

actor "Abogado Principal" as AB

rectangle "MS Casos Legales" {
  usecase "CU-AB-11\nRegistrar Resolución" as CU11
}

AB --> CU11

note right of CU11
  CasoController
  registra la resolución
  legal del caso
end note

@enduml