@startuml
skinparam classAttributeIconSize 0
hide empty members

class AbogadoPrincipal {
  - idAbogado: UUID
}

class AbogadoAsistente {
  - idAsistente: UUID
}

class Documento {
  - idDocumento: UUID
  - nombreArchivo: String
  - urlUbicacion: String
  - fechaSubida: DateTime
  - estado: EstadoDocumento
}

class RegistroAuditoria {
  - idRegistro: UUID
  - accionRealizada: String
  - fechaAccion: DateTime
  - usuarioId: UUID
}

enum EstadoDocumento {
  CARGANDO
  DISPONIBLE
  ARCHIVADO
}

AbogadoPrincipal "1" -- "0..*" Documento : sube / descarga >
AbogadoAsistente "1" -- "0..*" Documento : sube / descarga >

AbogadoPrincipal "1" -- "0..*" RegistroAuditoria : audita accesos (UC3) >
Documento "1" *-- "0..*" RegistroAuditoria : genera logs >
@enduml