@startuml
skinparam classAttributeIconSize 0
hide empty members

class AbogadoPrincipal {
  - idAbogado: UUID
}

class AbogadoAsistente {
  - idAsistente: UUID
}

class CasoLegal {
  - idCaso: UUID
  - numeroExpediente: String
  - fechaApertura: Date
  - estado: EstadoCaso
  + actualizarEstado(nuevoEstado: EstadoCaso): void
  + cerrarCaso(): void
}

class ActuacionProcesal {
  - idActuacion: UUID
  - detalle: String
  - fechaRegistro: DateTime
  - registradoPor: UUID
}

class Resolucion {
  - idResolucion: UUID
  - veredicto: String
  - fechaFallo: Date
}

enum EstadoCaso {
  ABIERTO
  EN_TRAMITE
  RESUELTO
  CERRADO
}

AbogadoPrincipal "1" -- "0..*" CasoLegal : crea y cierra >
AbogadoAsistente "1" -- "0..*" CasoLegal : asiste en >

CasoLegal "1" *-- "0..*" ActuacionProcesal : forma el historial (UC6) >
CasoLegal "1" -- "0..1" Resolucion : culmina con (UC4) >
CasoLegal -> EstadoCaso : posee >
@enduml